name: Testing

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - 'docs/**'
      - README.md
      - .gitignore
  workflow_dispatch:

jobs:
  call-regression-test:
    name: "Regression test"
    uses: xenanetworks/xoa-regression-tests/.github/workflows/execute-test-suite-denmark-tester.yml@fch-actions
    secrets: inherit